### ISSUE TITLE
Feature: modifications log that tracks original state for easy rollbacks

### ISSUE THREAD

**Issue by kmcquade** [salesforce/metabadger#16]
Example: a new run of the tool will create `~/.metabadger/2021-06-24-1416Z-modifications.log`. Each line of the file contains JSON per instance that logs the instance ID, region, and original status. then metabadger can apply that file to restore the original state. 

This way, you can blindly revert to what it was before, without downgrading some instances that were previously IMDSv2 before down to v1.

**Comment by ashishpatel-git** [comment]
**Metabadger.log** file gets created with timestamp and enforcement details now
